In [1]:
# Exercise 1 : Array Creation and Manipulation

import numpy as np

array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
# Exercise 2 : Type Conversion and Array Operations

import numpy as np

lst_float = [3.14, 2.17, 0, 1, 2]
array_float = np.array(lst_float)
array_int = array_float.astype(int)
print(array_int)


[3 2 0 1 2]


In [3]:
# Exercise 3 : Working with Multi-Dimensional Arrays

import numpy as np

arr_2d = np.arange(1,10).reshape(3,3)
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

import numpy as np

arr_rand = np.random.rand(4,5)
print(arr_rand)

[[0.66346234 0.47312075 0.52821814 0.77102834 0.03359303]
 [0.96358646 0.8832851  0.23392338 0.67458129 0.64389156]
 [0.59218686 0.26343714 0.31942727 0.67598042 0.88525614]
 [0.43488163 0.60609513 0.2011451  0.87667694 0.520156  ]]


In [5]:
# Exercise 5 : Indexing Arrays

import numpy as np

array = np.array(
    [[21, 22, 23, 22, 22], [20, 21, 22, 23, 24], [21, 22, 23, 22, 22]])
print(array[1])


[20 21 22 23 24]


In [6]:
# Exercise 6 : Reversing elements

import numpy as np

arr = np.arange(10)
arr_inv = arr[::-1]
print(arr_inv)

[9 8 7 6 5 4 3 2 1 0]


In [7]:
# Exercise 7 : Identity Matrix

import numpy as np

identity = np.identity(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# 🌟 Exercise 8 : Simple Aggregate Funcs

import numpy as np

arr = np.arange(10)

sum = np.sum(arr)
mean = np.mean(arr)
print(f"Sum: {sum}, Average: {mean}")

Sum: 45, Average: 4.5


In [9]:
# 🌟 Exercise 9 : Create Array and Change its Structure

import numpy as np

arr_1d = np.arange(1,21)
arr_2d = arr_1d.reshape(4,5)
print(arr_1d)
print(arr_2d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [10]:
# 🌟 Exercise 10 : Conditional Selection of Values

import numpy as np

arr = np.arange(10)
arr_even = arr[arr%2 != 0]

print(arr)
print(arr_even)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
